apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  InventoryService__BaseUrl: http://inventory-service:8080
  InventoryService__GrpcBaseUrl: http://inventory-service:8081
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
